# Site settings
title: "DoMyung Kim Resume"
description: "DoMyung Kim Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "DoMyung Kim(김도명)"
resume_title:                   "Introduce"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sagida2514@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-6391-2514"
resume_contact_address:         ""

resume_header_contact_info:     "• 010-6391-2514 • sagida2514@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>2021년 11월부터 게임개발에 입문하였으며, 현재 게임 클라이언트 개발과 스타트업 개발자로서 다양한 경험이 있습니다. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_skills:          true
resume_section_experience:      true
resume_section_projects:        true
resume_section_education:       true
resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
#resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sagida2514"
  resume_linkedin_url:          "https://www.linkedin.com/in/do-myung-kim-1ba76b22a/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

